In [ ]:
import tensorflow as tf
import numpy as np


In [ ]:
corpora_test_x = np.load('../08_test/corpora_test_x.npy')
target_test_y = np.load('../08_test/target_test_y.npy')

In [ ]:
corpora_test_x.shape

(11544, 618, 100, 1)

In [ ]:
target_test_y.shape

(11544, 2)

In [ ]:
print(target_test_y[0])

[1 0]


In [ ]:
n_samples = 2
x = corpora_test_x[0:n_samples]
y = target_test_y[0:n_samples]

x = np.reshape(x, [n_samples*618*100*1,])
y = np.reshape(y, [n_samples*2,])

output_filename = "testdata.tfrecord"

writer = tf.io.TFRecordWriter(output_filename)


def float_feature(value):
    return tf.train.Feature(float_list=tf.train.FloatList(value=value))

def int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))

feature_dict = {
    'x': float_feature(x),
    'y': int64_feature(y),
    'numberOfSamples': int64_feature([n_samples])
}

example = tf.train.Example(features=tf.train.Features(feature=feature_dict))

writer.write(example.SerializeToString())
writer.close()

In [ ]:
import tensorflow as tf
print(type(corpora_test_x))
t = tf.convert_to_tensor(x)
print(t)

<class 'numpy.ndarray'>
tf.Tensor(
[[[[ 1.83605969e-01]
   [-1.00894503e-01]
   [ 4.13140059e-01]
   ...
   [-8.82611349e-02]
   [-1.49526700e-01]
   [ 1.83730982e-02]]

  [[ 4.44124341e-01]
   [ 1.63826212e-01]
   [ 8.76851797e-01]
   ...
   [ 1.44601405e-01]
   [-5.40011108e-01]
   [ 5.38099408e-01]]

  [[ 1.83605969e-01]
   [-1.00894503e-01]
   [ 4.13140059e-01]
   ...
   [-8.82611349e-02]
   [-1.49526700e-01]
   [ 1.83730982e-02]]

  ...

  [[ 0.00000000e+00]
   [ 0.00000000e+00]
   [ 0.00000000e+00]
   ...
   [ 0.00000000e+00]
   [ 0.00000000e+00]
   [ 0.00000000e+00]]

  [[ 0.00000000e+00]
   [ 0.00000000e+00]
   [ 0.00000000e+00]
   ...
   [ 0.00000000e+00]
   [ 0.00000000e+00]
   [ 0.00000000e+00]]

  [[ 0.00000000e+00]
   [ 0.00000000e+00]
   [ 0.00000000e+00]
   ...
   [ 0.00000000e+00]
   [ 0.00000000e+00]
   [ 0.00000000e+00]]]


 [[[-1.20069742e-01]
   [-1.89845666e-01]
   [ 5.48323989e-01]
   ...
   [ 2.82734275e-01]
   [ 4.18062419e-01]
   [-4.47016567e-01]]

  [[ 3.7522

In [ ]:
x = t
ds = (tf.data.Dataset.from_tensors(x)
      .map(tf.io.serialize_tensor))
print(ds)
writer = tf.data.experimental.TFRecordWriter('temp.tfrecord')
writer.write(ds)

<MapDataset shapes: (), types: tf.string>


In [ ]:
#x = tf.constant([[2.0, 3.0, 3.0],[1.0, 5.0, 9.0]], dtype='float32')
x = t

# Write to file
ds = (tf.data.Dataset.from_tensors(x)
      .map(tf.io.serialize_tensor))
writer = tf.data.experimental.TFRecordWriter('temp.tfrecord')
writer.write(ds)
# Read from file
parse_tensor_f32 = lambda x: tf.io.parse_tensor(x, tf.float32)
ds2 = (tf.data.TFRecordDataset('temp.tfrecord')
       .map(parse_tensor_f32))
for x2 in ds2:
    tf.print(x2)

[[[[0.183605969]
   [-0.100894503]
   [0.413140059]
   ...
   [-0.0882611349]
   [-0.1495267]
   [0.0183730982]]

  [[0.444124341]
   [0.163826212]
   [0.876851797]
   ...
   [0.144601405]
   [-0.540011108]
   [0.538099408]]

  [[0.183605969]
   [-0.100894503]
   [0.413140059]
   ...
   [-0.0882611349]
   [-0.1495267]
   [0.0183730982]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[-0.120069742]
   [-0.189845666]
   [0.548324]
   ...
   [0.282734275]
   [0.418062419]
   [-0.447016567]]

  [[0.0375225]
   [0.0672809109]
   [-0.00819841586]
   ...
   [0.43716538]
   [0.429589301]
   [0.21258986]]

  [[-0.161430746]
   [-3.04209161]
   [2.46185493]
   ...
   [3.41101789]
   [-2.11922836]
   [4.0704608]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[1.

AttributeError: module 'tensorflow' has no attribute 'python_io'